name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch latest data
      run: |-
        curl https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_data | jq . > states.json
        curl https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_county_condensed_data | jq . > counties.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |-
        pip install -r requirements.txt
    - name: Build SQLite database
      run: python build_database.py
    - name: Deploy database to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        datasette publish vercel cdc.db \
          --title "CDC vaccination numbers" \
          --about "simonw/cdc-vaccination-history" \
          --about_url "https://github.com/simonw/cdc-vaccination-history" \
          --source "CDC" \
          --source_url "https://covid.cdc.gov/covid-data-tracker/#vaccinations" \
          --install datasette-vega \
          --install datasette-graphql \
          --project cdc-vaccination-history \
          --token $VERCEL_TOKEN \
          --extra-options "--setting sql_time_limit_ms 5000 --facet_time_limit_ms 3000"
